// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs6I_wx9gKg5QAAYeQAoukh_DvNtCZQr0',
    appId: '1:748280935846:web:1e8000f0495762c8108b67',
    messagingSenderId: '748280935846',
    projectId: 'spacehub-4da14',
    authDomain: 'spacehub-4da14.firebaseapp.com',
    storageBucket: 'spacehub-4da14.firebasestorage.app',
    measurementId: 'G-NSVYYG054M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Y_cC4tWuJBt-kkjjK4API1jhNHH28cI',
    appId: '1:748280935846:android:353fbcb143dc500e108b67',
    messagingSenderId: '748280935846',
    projectId: 'spacehub-4da14',
    storageBucket: 'spacehub-4da14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB76DrWg94COgI5Xc28PvGj1i3VvOZwkhY',
    appId: '1:748280935846:ios:011731db4669a00e108b67',
    messagingSenderId: '748280935846',
    projectId: 'spacehub-4da14',
    storageBucket: 'spacehub-4da14.firebasestorage.app',
    iosBundleId: 'com.example.spacehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB76DrWg94COgI5Xc28PvGj1i3VvOZwkhY',
    appId: '1:748280935846:ios:011731db4669a00e108b67',
    messagingSenderId: '748280935846',
    projectId: 'spacehub-4da14',
    storageBucket: 'spacehub-4da14.firebasestorage.app',
    iosBundleId: 'com.example.spacehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs6I_wx9gKg5QAAYeQAoukh_DvNtCZQr0',
    appId: '1:748280935846:web:1516291818898b08108b67',
    messagingSenderId: '748280935846',
    projectId: 'spacehub-4da14',
    authDomain: 'spacehub-4da14.firebaseapp.com',
    storageBucket: 'spacehub-4da14.firebasestorage.app',
    measurementId: 'G-LJN4XVR5TW',
  );
}
